package idv.rickyjian.vo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name = "user_account", schema = "dbo", catalog = "springpractice")
public class UserAccount implements java.io.Serializable {

	private String userName;
	private String password;
	private String gender;

	public UserAccount() {
	}

	public UserAccount(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}
	

	public UserAccount(String userName, String password, String gender) {
		this.userName = userName;
		this.password = password;
		this.gender = gender;
	}

	@Id

	@Column(name = "user_name", unique = true, nullable = false, length = 25)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@Column(name = "gender", nullable = true, length = 10)
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
}
